spring.application.name=microservice2
server.port=8082

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1

# ===============================
# ADMIN CLIENT CONFIG
# ===============================
spring.boot.admin.client.url=http://localhost:8080

# 🔥 IMPORTANT (use 8082 here)
spring.boot.admin.client.instance.service-base-url=http://127.0.0.1:8082
spring.boot.admin.client.instance.management-base-url=http://127.0.0.1:8082

# ===============================
# ACTUATOR CONFIG
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#management.server.base-path=/actuator